#!/bin/bash

npm install

CI=true bower install --allow-root

( cd src/server && bundle --path=/root/.gem/ruby/1.9.1 )

# symlink our VM cache into the container gem path
rm -rf /var/lib/gems/1.9.1/gems/multi_json-1.10.1
ln -snf /root/.gem/ruby/1.9.1/ruby/1.9.1/gems/* /var/lib/gems/1.9.1/gems/
ln -snf /root/.gem/ruby/1.9.1/ruby/1.9.1/specifications/* /var/lib/gems/1.9.1/specifications/

exec grunt dev
