#!/usr/bin/env bash
SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

WORKSPACE_HOMEDIRS=${WORKSPACE_HOMEDIRS:?"env WORKSPACE_HOMEDIRS must be defined"}
WORKSPACE_USERNAME=${WORKSPACE_USERNAME:?"env WORKSPACE_USERNAME must be defined"}
WORKSPACE_PUBLIC_KEY=${WORKSPACE_PUBLIC_KEY?"env WORKSPACE_PUBLIC_KEY must be defined"}

id -u $WORKSPACE_USERNAME &>/dev/null || adduser --home $WORKSPACE_HOMEDIRS/$WORKSPACE_USERNAME --disabled-password --gecos "" $WORKSPACE_USERNAME
adduser $WORKSPACE_USERNAME docker
rsync -rtv $SCRIPT_DIR/workspace_skel/ $WORKSPACE_HOMEDIRS/$WORKSPACE_USERNAME/

echo $WORKSPACE_PUBLIC_KEY >> $WORKSPACE_HOMEDIRS/$WORKSPACE_USERNAME/.ssh/authorized_keys

chown -R $WORKSPACE_USERNAME:$WORKSPACE_USERNAME $WORKSPACE_HOMEDIRS/$WORKSPACE_USERNAME

